CREATE TABLE IF NOT EXISTS `user` (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    ROLE VARCHAR(32) NOT NULL DEFAULT 'USER',
    AVATAR_URL VARCHAR(512),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    PRIMARY KEY (ID),
    UNIQUE (USERNAME),
    UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS `image_record` (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    STYLE_ID BIGINT,
    TYPE VARCHAR(32) NOT NULL,
    INPUT_CONTENT CLOB,
    OUTPUT_CONTENT CLOB,
    IMAGE_URL VARCHAR(512),
    STATUS VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY BIGINT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `style` (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DESIGNER_ID BIGINT NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    DESCRIPTION CLOB,
    PREVIEW_URL VARCHAR(512),
    CONFIG CLOB,
    STATUS VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_BY BIGINT,
    PRIMARY KEY (ID),
    UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS `system_config` (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CONFIG_KEY VARCHAR(128) NOT NULL,
    CONFIG_VALUE VARCHAR(1024),
    DESCRIPTION VARCHAR(512),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    PRIMARY KEY (ID),
    UNIQUE (CONFIG_KEY)
);

CREATE TABLE IF NOT EXISTS `audit_log` (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OPERATION_TYPE VARCHAR(64) NOT NULL,
    TARGET_TYPE VARCHAR(64) NOT NULL,
    TARGET_ID BIGINT,
    OPERATOR_ID BIGINT,
    BEFORE_DATA CLOB,
    AFTER_DATA CLOB,
    IP_ADDRESS VARCHAR(64),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

-- 注意：初始化数据由 DataInitializer.java 在应用启动时自动创建
-- 包括：admin@nebula.com, designer@nebula.com, user@nebula.com 用户
-- 以及系统配置和默认风格数据



